site_name: Documentation
pages:
- Home: index.md
- Technology:
  - Ubuntu:
    - 'Initial Server Setup with Ubuntu 16.04': technology/ubuntu/initial.md
    - 'How To Set Up Apache Virtual Hosts on Ubuntu 16.04': technology/ubuntu/vhost.md
theme: readthedocs
